// packages/taro-platform-harmony-hybrid/components-library/src/components/video/video.tsx
import { Component, ComponentInterface, Event, EventEmitter, h, Host, Prop, Watch } from '@stencil/core'

let videoId = 0
interface needToUpdateProps{
  componentId?:string
  width?:number
  height?:number
  src?:string
  controls?:boolean
  autoPlay?:boolean
  muted?:boolean
  loop?:boolean
  objectFit?:string
}
@Component({
  tag: 'taro-video-core',
  styleUrl: './style/index.scss'
})
export class Video implements ComponentInterface {
  /**
   * 视频播放器宽度
   */
  @Prop() hosWidth: number

  /**
   * 视频播放器高度
   */
  @Prop() hosHeight: number

  /**
   * 要播放视频的资源地址
   */
  @Prop() src: string

  /**
   * 是否显示默认播放控件（播放/暂停按钮、播放进度、时间）
   */
  @Prop() controls = true

  /**
   * 是否自动播放
   */
  @Prop() autoplay = false

  /**
   * 是否循环播放
   */
  @Prop() loop = false

  /**
   * 是否静音播放
   */
  @Prop() muted = false

  /**
   * 当视频大小与 video 容器大小不一致时，视频的表现形式
   */
  @Prop() objectFit: 'contain' | 'fill' | 'cover' = 'contain'

  @Event({
    eventName: 'play'
  }) onPlay: EventEmitter

  @Event({
    eventName: 'pause'
  }) onPause: EventEmitter

  @Event({
    eventName: 'ended'
  }) onEnded: EventEmitter

  @Event({
    eventName: 'timeupdate'
  }) onTimeUpdate: EventEmitter

  @Event({
    eventName: 'error'
  }) onError: EventEmitter

  @Event({
    eventName: 'seeked'
  }) onSeeked: EventEmitter

  @Event({
    eventName: 'seeking'
  }) onSeeking: EventEmitter

  private componentId: string
  private needToUpdate: needToUpdateProps = {}

  constructor () {
    this.componentId = `video_${videoId++}`
    this.needToUpdate.componentId = this.componentId
  }

  @Watch('hosWidth')
  hosWidthChanged (newVal: number) {
    this.needToUpdate.width = newVal
  }

  @Watch('hosHeight')
  hosHeightChanged (newVal: number) {
    this.needToUpdate.height = newVal
  }

  @Watch('src')
  srcChanged (newVal: string) {
    this.needToUpdate.src = newVal
  }

  @Watch('controls')
  controlsChanged (newVal: boolean) {
    this.needToUpdate.controls = newVal
  }

  @Watch('autoplay')
  autoplayChanged (newVal: boolean) {
    this.needToUpdate.autoPlay = newVal
  }

  @Watch('loop')
  loopChanged (newVal: boolean) {
    this.needToUpdate.loop = newVal
  }

  @Watch('muted')
  mutedChanged (newVal: boolean) {
    this.needToUpdate.muted = newVal
  }

  @Watch('objectFit')
  objectFitChanged (newVal: string) {
    this.needToUpdate.objectFit = newVal
  }

  componentWillLoad (): void | Promise<void> {
    this.transferVideoProps()
  }

  componentWillUpdate (): void | Promise<void> {
    // @ts-ignore  调用JSB方法更新原生组件数据
    window.JSBridge.transferSameLayerArgs(this.needToUpdate)
    this.needToUpdate = { componentId: this.componentId }
  }

  
  handleOnPlay = (e: any) => {
    this.onPlay.emit(e)
  }
  
  handleOnPause = (e: any) => {
    this.onPause.emit(e)
  }

  handleOnFinish = (e: any) => {
    this.onEnded.emit(e)
  }

  handleOnUpdate = (e: any) => {
    this.onTimeUpdate.emit(e)
  }

  handleOnError = (e: any) => {
    this.onError.emit(e)
  }

  handleOnSeeked = (e: any) => {
    this.onSeeked.emit(e)
  }

  handleOnSeeking = (e: any) => {
    this.onSeeking.emit(e)
  }


  transferVideoProps () {
    // 同层渲染video组件数据
    const {  
      hosWidth,  
      hosHeight,  
      src,  
      controls,  
      autoplay,  
      loop,  
      muted,
      objectFit
    } = this
  
    const properties = {
      componentId: this.componentId,
      width: hosWidth,
      height: hosHeight,
      src: src,
      controls: controls,
      autoPlay: autoplay,
      loop: loop,
      muted: muted,
      objectFit: objectFit,
      onPlay: this.handleOnPlay,
      onPause: this.handleOnPause,
      onFinish: this.handleOnFinish,
      onUpdate: this.handleOnUpdate,
      onError: this.handleOnError,
      onSeeked: this.handleOnSeeked,
      onSeeking: this.handleOnSeeking
    }
  
    // @ts-ignore  调用JSB方法传递原生组件数据
    window.JSBridge.transferSameLayerArgs(properties)
  }

  render () {
    const {
      hosWidth,
      hosHeight
    } = this

    return (
      <Host>
        <embed id={this.componentId} type='native/video' width={hosWidth} height={hosHeight}/>
      </Host>
    )
  }
}

// packages/taro-platform-harmony-hybrid/src/components/components-react/video/Video.tsx
import React, { Component, SyntheticEvent } from 'react'

let videoId = 0
interface VideoProps extends React.HTMLAttributes<HTMLElement> {
  hosWidth?: number
  hosHeight?: number
  src?: string
  controls?: boolean
  autoPlay?: boolean
  loop?: boolean
  muted?: boolean
  objectFit?: 'contain' | 'fill' | 'cover'
  onPlay?: (e: SyntheticEvent) => void
  onPause?: (e: SyntheticEvent) => void
  onEnded?: (e: SyntheticEvent) => void
  onTimeUpdate?: (e: SyntheticEvent) => void
  onError?: (e: SyntheticEvent) => void
  onSeeked?: (e: SyntheticEvent) => void
  onSeeking?: (e: SyntheticEvent) => void
}

interface needToUpdateProps {
  componentId?: string
  width?: number
  height?: number
  src?: string
  controls?: boolean
  autoPlay?: boolean
  muted?: boolean
  loop?: boolean
  objectFit?: string
}
class Video extends Component<VideoProps> {
  private componentId: string
  private needToUpdate: needToUpdateProps = {}

  constructor (props: VideoProps) {
    super(props)
    this.componentId = `video_${videoId++}`
  }

  componentDidMount () {
    this.transferVideoProps()
  }

  componentDidUpdate () {
    // @ts-ignore  调用JSB方法更新原生组件数据
    window?.JSBridge?.transferSameLayerArgs(this.needToUpdate)
    this.needToUpdate.componentId = this.componentId
    this.componentId = `video_${videoId++}`
  }

  transferVideoProps () {
    const {
      hosWidth,
      hosHeight,
      src,
      controls,
      autoPlay,
      loop,
      muted,
      objectFit,
      onPlay,
      onPause,
      onEnded,
      onTimeUpdate,
      onError,
      onSeeked,
      onSeeking,
    } = this.props

    const properties = {
      componentId: this.componentId,
      width: hosWidth,
      height: hosHeight,
      src: src,
      controls: controls,
      autoPlay: autoPlay,
      loop: loop,
      muted: muted,
      objectFit: objectFit,
      onPlay: onPlay,
      onPause: onPause,
      onEnded: onEnded,
      onTimeUpdate: onTimeUpdate,
      onError: onError,
      onSeeked: onSeeked,
      onSeeking: onSeeking,
    }

    // Call JSB method to transfer native component data
    // Replace this line with your actual JSB method call
    // @ts-ignore
    window?.JSBridge?.transferSameLayerArgs(properties)
  }

  render (): React.ReactNode {
    const { hosWidth, hosHeight } = this.props

    return (
      <div>
        <embed id={this.componentId} width={hosWidth} height={hosHeight} />
      </div>
    )
  }
}

export default Video
